apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-clone-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/junaidzeb123/DevSecOps-Project.git
    targetRevision: HEAD
    path: Kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
